require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Packaging/RequireRelativeHardcodingLib:
  Exclude:
    - bin/**/*
    - spec/**/*

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

RSpec/MultipleMemoizedHelpers:
  Max: 9